BeeBombshell/Python-DSA

README.md
=> Added Sorting Algorithms

README.md
=> Added Linear Search in README.md

bfs.py, dfs.py
Added Breadth First Search and Depth First Search algorithms in python
=> Added bfs and dfs search algorithms

Stack Algorithms
I have created this file. Here, I have mention how to create a stack, add an element and delete it. Kindly review it and merge it. In case of any conflict, let me know.
=> Create Stack Algorithms

DSA/dictionary.py
=> added code for dictionary

DSA/tuples.py
=> added code for tuples

DSA/arrays.py, DSA/lists.py
=> created a folder named DSA and wrote code for arrays

DSA/LinkedList.py
This is my program for Linked List which contains all the basic functions of adding, deleting, inserting, displaying nodes.
=> Added Linked List program with detailed functionalities  (issue resolved #42)

Sorting Algorithms/bubble_sort.py
Added optimized function for Bubble Sort.
If no elements are swapped, then the list is already sorted and the control will come out of the loop.
=> Added optimized function for bubble sort.

README.md, Recursion/Factorial_Recursion.py, Recursion/Fibonacci_Series.py
Programs on Recursion -
1. Factorial of a number.
2. Fibonacci Series
=> Added two programs on Recursion

Sorting Algorithms/countSort.py
Added count sort in python.
Issue #42
=> Added count sort

Sorting Algorithms/mergesort.py
Added a new sorting algorithm to your repo. Please merge and don't forget to give hacktoberfest accepted tag if you can.
=> added mergesort function

DSA/Stack Algorithms
=> Update Stack Algorithms by saurav

Recursion/Reversing a string using Recursion.py, Tree Data Structure/Heapq in python.py
#hacktoberfest #hacktoberfest-accepted #contribute #open-source #hacktoberfest2022
=> Initial Commit

DSA/Stack Algorithms
=> Update Stack Algorithm

Sort-all/bubble.py, Sort-all/bucket.py, Sort-all/counting.py, Sort-all/insertion.py, Sort-all/merge.py, Sort-all/quick.py, Sort-all/selection.py, Sort-all/sortall.md
Added all sorting algo with code in python
=> sort-all-added

DSA/circularLinkedList.py
Added script for creating circular single linked lists using OOP.
=> Circular Linked List

Search Algorithms/Fibonacci-Search/README.md, Search Algorithms/Fibonacci-Search/fibonacci_search.py
Hey, Have added fibonacci search along with its readme file which includes a gist of topic and its algorithm.
Do have a look to it and let me know if needed any changes. 
Thanks.
=> Added fibonacci search to search section along with its Readme

README.md
Added new topics in DSA like Morris Traversal and do while loop
according to issue #2
=> Added Morris Traversal Topic In ReadMe & do While

Tree Data Structure/morris_traversal.py
Added code for morris traversal as morris_traversal.py in binary tree data structure
According to issue #4
=> Code for Morris Traversal in Binary Tree

README.md, Recursion/Ackermann.py
Added Ackermann function in recursion. Please Kindly check and merge the pull request.
=> Ackermann.py added in recursion

Backtracking/Knights_tour.py, Backtracking/N_queens.py
@BeeBombshell @BhavyaT-135 I have added both the solutions. Will add more soon.
=> Added backtracking solutions for knights_tour and n_queens

DSA/find_Insert_position.py
Python program to search the insert position of K in a sorted array
=> added a classic dsa problem

Merge Sort
This code takes input array from user and gives out sorted array. Time Complexity is O(n log(n))
=> Merge Sort code in Python
